%% This code is used to plot the knockdown time and average velocity curves.
% The bioassay data of D. melanogaster exposed to 2.0 mg of Forms I and II
% were shown here as an example.
clc;
clear;
%% Figure 2F
Delta = readtable('D. melanogaster_DMdusts KT.xlsx','Range','B1:D55');%read the dataset of knockdown time. '262ANV01' correspond to the 
ax1 = subplot(2,1,2);
x1=Delta{:,2};
x2=Delta{:,3};
y=Delta{:,1};
plot(ax1, x1,y,'.', x2,y,'.','MarkerSize',20)
pbaspect([2 1 1]) % relative lengths of each axis.
ax = gca;%ax. FontName= arial;
ax.FontSize = 25;% axis fontsize.
ax.LineWidth = 2;% axis LineWidth
xlabel('Time (min)','FontSize',25) %label fontsize
ylabel('Percentage Knockdown','FontSize',25) %label fontsize
xlim([0 300])
xticks(0:50:800)
yticks(0:25:100)
%% Figure 2E
load 'D. melanogaster_DMdusts_velocity.mat'%read the dataset of average velocity.The data can be generated by  'Act_anals.m'
start=1;
final=750;
period=180;
xxx=(start:final);
yy1=sum(reshape(actv_velocity_m(1+(start-1)*period:final*period,11),period,final-start+1));
yy2=sum(reshape(actv_velocity_m(1+(start-1)*period:final*period,12),period,final-start+1));
yy3=sum(reshape(actv_velocity_m(1+(start-1)*period:final*period,13),period,final-start+1));
sy1=smoothdata(yy1,'sgolay');%smooth data
sy2=smoothdata(yy2,'sgolay');
sy3=smoothdata(yy3,'sgolay');
ax2 = subplot(2,1,1);
set(gcf,'DefaultAxesColorOrder',[0, 0.4470, 0.7410;0.8500, 0.3250, 0.0980;0, 0.4470, 0.7410;0.8500, 0.3250, 0.0980])
plot(ax2,xxx,yy2,'.',xxx,yy3,'.',xxx,sy2,'-',xxx,sy3,'-','MarkerSize',12, 'LineWidth',4);
pbaspect([2 1 1]) % relative lengths of each axis.
ax = gca;%ax. FontName= arial;
ax.FontSize = 25;% axis fontsize.
ax.LineWidth = 2;% axis LineWidth
xlabel('Time (min)','FontSize',25)
ylabel('Average Velocity (cm/min)','FontSize',25)
xlim([0 300])
xticks(0:50:800)
yticks(0:1.5:6)
ylim([0 6])
x=sum(yy3(200:700))/500;

%%
print -r300 Figure_2E_2F.tif